name: refri_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-322.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  provider: ^6.0.5
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  csv: ^5.0.1
  get_it: ^7.2.0
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.3
  convex_bottom_bar: ^3.2.0
  flutter_native_splash: ^2.2.19
  google_sign_in: ^6.0.2
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_messaging: ^14.4.0
  firebase_crashlytics: ^3.1.0
  firebase_auth: ^4.4.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/img/
    - asset/svg/
  fonts:
    - family: SpoqaHanSans
      fonts:
        - asset: asset/font/SpoqaHanSansNeo-Bold.otf
          weight: 700
        - asset: asset/font/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: asset/font/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: asset/font/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: asset/font/SpoqaHanSansNeo-Thin.otf
          weight: 100
