// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpQPFEo0phWzpJJFMWqXnKa-uZwPxt04',
    appId: '1:66132228049:web:4080fa69fc70068e6f12f0',
    messagingSenderId: '66132228049',
    projectId: 'poetic-torch-381606',
    authDomain: 'poetic-torch-381606.firebaseapp.com',
    storageBucket: 'poetic-torch-381606.appspot.com',
    measurementId: 'G-S4XLK02RZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoKWArdhJMfM-rDWm5auts6OmdytcJkf4',
    appId: '1:66132228049:android:97bbf3dfd1cccdd66f12f0',
    messagingSenderId: '66132228049',
    projectId: 'poetic-torch-381606',
    storageBucket: 'poetic-torch-381606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJv0VLhAc9wJ-1Z7l9iPjx0VAehDOUkk',
    appId: '1:66132228049:ios:280cf024a5dcaa8a6f12f0',
    messagingSenderId: '66132228049',
    projectId: 'poetic-torch-381606',
    storageBucket: 'poetic-torch-381606.appspot.com',
    iosClientId: '66132228049-ibo8l7hgjqklt9r055qn1f30q16hltuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.refriMobile',
  );
}
